<script lang="ts">
import Vue from "vue";
import { DayType, DayTypeDescriptions } from "@/day-types";
export default Vue.extend({
	name: "Day",
	props: {
		day: Number,
		test: Object,
		type: Number,
		start: Number,
		duration: Number,
		selection: Array
	},
	computed: {
		display_text(): string {
			switch (this.type) {
				case DayType.shift:
					return `${this.start} - ${(this.duration + this.start) % 24}`;
				case DayType.unpaid:
					return this.is_sunday ? "P" : "SZ"
				default:
					return DayTypeDescriptions[this.type].label
			}
		},
		style(): any {
			//We can't use purely type_string because that conflicts with
			//classes generated by vuetify based on theme colors
			return ['t-' + this.type_string, {
				'selected': this.is_selected,
				'weekend': this.is_weekend,
				'last': this.selection[this.selection.length - 1] == this.day,
				'first': this.selection[0] == this.day
			}]
		},
		color(): string {
			return DayTypeDescriptions[this.type].color
		},
		type_string(): string {
			return Object.entries(DayType)[this.type][1] as string
		},
		is_selected(): boolean {
			return this.selection.includes(this.day)
		},
		is_weekend(): boolean {
			let dayOfWeek = this.to_date.getDay()
			return (dayOfWeek === 6) || (dayOfWeek === 0); // 6 = Saturday, 0 = Sunday
		},
		is_sunday(): boolean {
			let dayOfWeek = this.to_date.getDay()
			return (dayOfWeek === 0); // 0 = Sunday
		},
		to_date(): Date {
			let sheet = this.$store.state.sheets.sheet
			return new Date(sheet.year, sheet.month, this.day)
		}

	},
});
</script>

<template>
	<td :class="style" :style="{backgroundColor: color}">
		{{ display_text }}
	</td>
</template>

<style scoped>
td:hover {
	/* background-color: #ddd; */
	filter: brightness(70%);
	cursor: pointer;
}
td {
	border: 0.5px solid #ccc;
	text-align: center;
	min-width: 3.75em;
	text-shadow: white 0px 0px 20px;
	font-weight: 500;
	letter-spacing: 1px;
}
.selected {
	border-top-color: var(--v-selected-border-base);
	border-bottom-color: var(--v-selected-border-base);
	background-color: #ccc;
	text-align: center;
	filter: brightness(90%);
}
.weekend {
	filter: brightness(80%);
	z-index: -1;
}
.t-holiday,
.t-sick,
.t-weekend,
.t-unpaid {
	color: white;
	text-shadow: black 0px 0px 20px;
}
.t-weekend {
	filter: none;
}
.last.selected {
	border-right-color: var(--v-selected-border-base);
}
.first.selected {
	border-left-color: var(--v-selected-border-base);
}
</style>