<script lang="ts">
import Vue from "vue";
import { DayType, DayTypeDescriptions } from "@/day-types";
import { last } from "lodash";
export default Vue.extend({
	name: "Day",
	props: {
		day: Number,
		test: Object,
		type: Number,
		start: Number,
		duration: Number,
		selection: Array
	},
	computed: {
		display_text(): string {
			if (this.type == DayType.shift) {
				return `${this.start} - ${(this.duration + this.start) % 24}`;
			} else if (this.type == DayType.unpaid) {
				return this.is_sunday ? "P" : "SZ"
			}
			else {
				return DayTypeDescriptions[this.type].label
			}
		},
		style(): string {
			 //We can't use purely type_string because that conflicts with
			 //classes generated by vuetify based on theme colors
			let style = "t-" + this.type_string

			if (this.is_selected) {
				style += " selected"
			}
			if (this.is_weekend) {
				style += " weekend"
			}
			if(this.is_last){
				style += " last"
			}
			if(this.is_first){
				style += " first"
			}
			// console.log(style)
			return style

		},
		color(): string {
			let from_desc = DayTypeDescriptions[this.type].color
			// if(this.type == DayType.empty || this.type == DayType.shift){
			//     return ""
			// }
			return from_desc
			// return ""
		},
		type_string(): string {
			return Object.entries(DayType)[this.type][1] as string
		},
		is_selected() : boolean{
			return this.selection.includes(this.day)
		},
		is_weekend(): boolean {
			let dayOfWeek = this.to_date.getDay()
			return (dayOfWeek === 6) || (dayOfWeek === 0); // 6 = Saturday, 0 = Sunday
		},
		is_sunday(): boolean {
			let dayOfWeek = this.to_date.getDay()
			return (dayOfWeek === 0); // 6 = Saturday, 0 = Sunday
		},
		is_last() : boolean{
			return this.selection[this.selection.length - 1] == this.day
		},
		is_first() : boolean{
			return this.selection[0] == this.day
		},
		to_date(): Date {
			let sheet = this.$store.state.sheets.sheet
			return new Date(sheet.year, sheet.month, this.day)
		}

	},
});
</script>

<template>
	<td :class="style" :style="{backgroundColor: color}">
		{{ display_text }}
	</td>
</template>

<style scoped>
td:hover {
	/* background-color: #ddd; */
	filter: brightness(70%);
	cursor: pointer;
}
td {
	border: 0.5px solid #ccc;
	text-align: center;
	min-width: 3.75em;
	text-shadow: white 0px 0px 20px;
	font-weight: 500;
	letter-spacing: 1px;
}
.selected {
	border: 0.5px solid #1f1f1f;
	background-color: #ccc;
	text-align: center;
	filter: brightness(90%);
	border-left-width: 0;
	border-right-width: 0;
}
.weekend {
	filter: brightness(80%);
	z-index: -1;
}
.t-holiday, .t-sick, .t-weekend, .t-unpaid{
	color: white;
	text-shadow: black 0px 0px 20px;
}
.t-weekend{
	filter: none
}
.last.selected{
	border-right-width: 1px;
}
.first.selected{
	border-left-width: 1px;
}
</style>