<script lang="ts">
import Vue from "vue";
import { DayType, DayTypeDescriptions } from "@/model/day-types";
import { FontColorFromBackground } from "@/utils/color-helpers"
import { isWeekend, isDay, isHoliday } from "@/utils/date-helpers"
export default Vue.extend({
	name: "Day",
	props: {
		day: Number,
		test: Object,
		type: Number,
		start: Number,
		duration: Number,
		selection: Array
	},
	computed: {
		display_text(): string {
			switch (this.type) {
				case DayType.shift:
					return `${this.start} <br> ${(this.duration + this.start) % 24}`;
				case DayType.unpaid:
					return this.is_sunday ? "P" : "SZ"
				default:
					return DayTypeDescriptions[this.type].label
			}
		},
		classes(): Array<any> {
			//We can't use purely type_string because that conflicts with
			//classes generated by vuetify based on theme colors
			return ['t-' + this.type_string, {
				'selected': this.is_selected,
				'weekend': this.is_weekend || this.is_holiday,
				'last': this.selection[this.selection.length - 1] == this.day,
				'first': this.selection[0] == this.day
			}]
		},
		type_string(): string {
			return Object.entries(DayType)[this.type][1] as string
		},
		is_selected(): boolean {
			return this.selection.includes(this.day)
		},
        to_date(): Date {
            let sheet = this.$store.state.sheets.sheet
            return new Date(sheet.year, sheet.month - 1, this.day)
        },
		is_weekend(): boolean {
            return isWeekend(this.to_date);
		},
		is_holiday(): boolean {
			return isHoliday(this.to_date)
		},
		is_sunday(): boolean {
            return isDay(this.to_date, 0) // 0 = Sunday
		},
		style(): unknown {
			const color = DayTypeDescriptions[this.type].color
			return { backgroundColor: color, color: FontColorFromBackground(color) }
		}

	},
});
</script>

<template>
    <td :class="classes" :style="style" v-html="display_text">
    </td>
</template>

<style scoped>
td:hover {
	/* background-color: #ddd; */
	filter: brightness(90%);
	cursor: pointer;
}
td {
	border: 0.5px solid #ccc;
	text-align: center;
	min-width: 2.7em;
    width: 100vw;
	height: 3.75em;
	text-shadow: white 0px 0px 20px;
	font-weight: 500;
	font-size: 15px;
	letter-spacing: 1px;
}
.selected {
	border-top-color: var(--v-selected-border-base);
	border-bottom-color: var(--v-selected-border-base);
	background-color: #ccc;
	text-align: center;
	filter: brightness(85%);
}
.last.selected {
	border-right-color: var(--v-selected-border-base);
}
.first.selected {
	border-left-color: var(--v-selected-border-base);
}
.weekend {
	filter: hue-rotate(-20deg);
	z-index: -1;
}
.weekend:hover {
	filter: brightness(90%) !important;
}
.weekend.t-empty,
.weekend.t-shift {
	filter: brightness(95%);
	z-index: -1;
}
.weekend.t-empty.selected,
.weekend.t-shift.selected {
	filter: brightness(80%);
}
</style>